language: rust
sudo: false
cache:
  directories:
  - "$HOME/.cargo"
os:
- linux
branches:
  only:
  - master
before_install:
- mkdir documentation
- rm -rf $HOME/.cargo/bin/mdbook
- cargo install mdbook
- export PATH=$PATH:$HOME/.cargo/bin
script:
- mdbook init
- mdbook build; cp -r book/* documentation
after_success:
- bash scripts/upload_doc.sh
env:
  global:
  - secure: Jc96i9nYYl1oh8nPgBWvBWXDsli7vKHBE0bE8vGQcpahtQCOuZyHrG7O/nRhSk5ikpK9fkHKcVn+k1lli8jnd83ZF1K+TmRppNu0QPsUY5ZUjBxJ56xL3H6/I6nWPItOH4vh8SI6uGkahrvm/QlxkhJSbk0cZlWw2tOeRMATh9PDWt6dPMBTtYmYRjI2f8CkS9h+l0pzfjQjQvCosNoJbek1Yhu5dxH5mvo4CTKiahZ3iH86n5Hu6UEFNP+73Z9qMUhz/ctc4T9yH2qxV9dPm3pWRdgwb8xLTn9/3H+T/9DlZTjs/HRrOtLOgm7ViE70YOBpp4DD3oqqmIMu2C+1X0xCVHZ3TR/7RAontxg5GeJDDD3cw2DE9mcChyeuLGTTJ2/HtKjMUhvPLz0c2QvnVFnmo8iERl5hpli7o9AEiHfaxoo3CzS8k3k0xc4pFU1d2Bejxe2l5xVGys55u6cl0c6Hyv2E+F2a4mAK9uQ3w+48vjsYfZK0xwWlBTcSwzbWPr0KnF0W4OGxQhPJSnCLp12W+6sX7Xr/NT89ay9wzDFyHsE41XkP6HQuH13D+gf5rmTkCDlbBsB/jvneSpdlhe9eEMBqheqopepvu0S9JuxOh+6xi5GX+9UTtCaQvMVL4Jl7Hntn9q02FrKljh4zLr3HFcYgYIUTsLqgtuIdAz4=
